default:
    index: /
    title: Cao Đẳng Công Nghệ Thông Tin Hữu Nghị Việt - Hàn
    sub_title: Trường công lập thuộc Bộ Thông Tin - Truyền Thông
    locale: vi-VN
    meta_description: Trường CĐ CNTT Việt Hàn, đào tạo các ngành công nghệ thông tin, điện tử viễn thông, quản trị kinh doanh, đồ họa máy tính.
    meta_tw_image:
    meta_og_image:

sub_index:
    index: /
    title: Cao Đẳng Công Nghệ Thông Tin Hữu Nghị Việt - Hàn
    sub_title: Trường công lập thuộc Bộ Thông Tin - Truyền Thông
    locale: vi-VN
    meta_description: Trường CĐ CNTT Việt Hàn, đào tạo các ngành công nghệ thông tin, điện tử viễn thông, quản trị kinh doanh, đồ họa máy tính.
    meta_tw_image:
    meta_og_image:

splash:
    index: /
    title: Cao Đẳng Công Nghệ Thông Tin Hữu Nghị Việt - Hàn
    sub_title: Trường công lập thuộc Bộ Thông Tin - Truyền Thông
    locale: vi-VN
    meta_description: Trường CĐ CNTT Việt Hàn, đào tạo các ngành công nghệ thông tin, điện tử viễn thông, quản trị kinh doanh, đồ họa máy tính.
    meta_tw_image:
    meta_og_image:

tuyensinh:
    index: /tuyensinh/
    title: Tuyển sinh 2017
    sub_title: Trường Cao Đẳng Công Nghệ Thông Tin Hữu Nghị Việt - Hàn
    locale: vi-VN
    meta_description: Năm 2017, trường CĐ CNTT Việt Hàn tuyển sinh và đào tạo các ngành công nghệ thông tin, điện tử viễn thông, quản trị kinh doanh, đồ họa máy tính.
    meta_tw_image:
    meta_og_image:

aciids:
    index: /aciids-2016/
    title: <span>Hội thảo </span>ACIIDS<span> lần thứ 8 - Đà Nẵng</span> 2016
    sub_title: Trường Cao Đẳng Công Nghệ Thông Tin Hữu Nghị Việt - Hàn
    locale: vi-VN
    meta_description: Hội thảo khoa học quốc tế ACIIDS 2016 lần thứ 8 diễn ra tại Đà Nẵng được tổ chức bởi Trường CĐ CNTT Hữu nghị Việt Hàn.
    meta_tw_image:
    meta_og_image:
    css:
        - aciids

aciids_en:
    index: /aciids-2016/en/
    title: <span>8th </span>ACIIDS<span> - Danang</span> 2016
    sub_title: Korea-Vietnam Friendship Information Technology College
    locale: en
    meta_description: ACIIDS 2016 by ViethanIT.
    meta_tw_image:
    meta_og_image:
    css:
        - aciids

cest:
    index: /cest-2017/
    title: <span>Hội thảo Khoa học giáo dục và Công nghệ </span>CEST 2017
    sub_title: Trường Cao Đẳng Công Nghệ Thông Tin Hữu Nghị Việt - Hàn
    locale: vi-VN
    meta_description: CEST2017 là diễn đàn giao lưu, thảo luận và công bố các công trình nghiên cứu của các giảng viên, nhà khoa học giữa ba trường CĐ Việt Hàn, CĐSP Huế và CĐ CN Huế.
    meta_tw_image:
    meta_og_image:
    css:
        - cest

10nam:
    index: /10-nam/
    title: ViethanIT 10 Năm<span> Xây dựng và Phát triển</span>
    sub_title: Trường Cao Đẳng Công Nghệ Thông Tin Hữu Nghị Việt - Hàn
    locale: vi-VN
    meta_description: Website chính thức về lễ kỷ niệm và các hoạt động chào mừng 10 năm hình thành, xây dựng và phát triển trường CĐ CNTT Hữu nghị Việt Hàn.
    meta_tw_image: /photo/10nam/site_image.jpg
    meta_og_image: /photo/10nam/site_image.jpg
    css:
        - 10nam

doanhnghiep:
    index: /
    title: Doanh nghiệp
    sub_title: Trường Cao Đẳng Công Nghệ Thông Tin Hữu Nghị Việt - Hàn
    locale: vi-VN
    meta_description: Trường CĐ CNTT Việt Hàn, đào tạo các ngành công nghệ thông tin, điện tử viễn thông, quản trị kinh doanh, đồ họa máy tính.
    meta_tw_image:
    meta_og_image:
